### ISSUE TITLE
Printer tolerance

### ISSUE THREAD

**Issue by STGRobotics** [open-dynamic-robot-initiative/open_robot_actuator_hardware#12]
Unable to print on school 3D printer until school reopen, I have a printer that the tolerance are different. I need to modify the following. Is it posible to get the step file. I was able to mod the body 

Actuator Module Shell Base
Actuator Module Shell Cover
Lower Leg Structure Base
Lower Leg Structure Fork
hip_aa_module_shell_base
hip_aa_module_shell_cover
hip_fe_module_shell_base
hip_fe_module_shell_cover
upper_leg_shell_base
upper_leg_shell_cover

**Comment by fgrimminger** [comment]
Sure - I uploaded the step files:
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/foot_contact_switch_v1/step_files
https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/quadruped_robot_12dof_v1/step_files

You won't need the actuator module - this version is only used for the Solo8 robot.
It's really the same part as the upper leg - except there are two attachment points and an opening for the wires. This is required, because the same module is used as an upper leg and a hip module for Solo8 (picture below).
I'll restructure and rename the files to make things clearer when I have time.

https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/tree/master/mechanics/actuator_module_v1/step_files

![actuator_module](https://user-images.githubusercontent.com/53785782/81819511-b15ec100-952f-11ea-9a9e-f1a8f597af04.png)

**Comment by STGRobotics** [comment]
Thank you
