### ISSUE TITLE
motorware repo not public yet

### ISSUE THREAD

**Issue by jviereck** [open-dynamic-robot-initiative/open_robot_actuator_hardware#2]
For flashing the firmware on the TI boards, we rely on the `motorware` repo from git-amd right now. This means anyone outside of amd-clmc won't be able to flash this board.

Is this a problem?

\cc @luator @vincentberenz

**Comment by luator** [comment]
We don't have a public fork of motorware due to an unclear legal situation (it is affected by some US export regulation...). However, we provide a patch with our modifications here: https://github.com/open-dynamic-robot-initiative/amd_motorware_ext. So people from outside have to download it from TI first and then can apply this patch.

**Comment by luator** [comment]
Closing this as WONTFIX. Feel free to re-open if there is still something to discuss.
