### ISSUE TITLE
Motor and sensor replacement questions for my practical local setup.

### ISSUE THREAD

**Issue by taskx6004** [open-dynamic-robot-initiative/open_robot_actuator_hardware#30]
Hi, I want to build a drive unit to test functionalities before building 12 units of them, with some modifications with motor and sensor, here's something would you please give me some hint:

1. 300KV 4004 from TMotor is way to expensive as a RC motor, I want to replace it with DJI Inspire 1/2 generation 3510H, same KV but smaller diameter. It has a shaft could be used as a pinon guide, and four quirky vertical tab for screw mounting. I think i can redesign the belt transmission so this is not an issue, it's for forking suggestion for people who want's build their own like me.

2. encoder: In the documenting [https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/dual_motor_testbed_v1/README.md#dual-motor-testbed-v1](here) claimed it has a 5000 pulses! AB encoding with times 4 on it so the resolution is 20000 per turn. it almost impractical in my sense for a motor like this. By taking this concern I looked for its datasheet: **CPR=625 and res = 5000**. An AS5047 magnetic encoder with 1000 CPR would worth a compatibility/performance test. And one more favorable feature is much easier to mount the small surface polarized tablet for sensing.

3. How to acquire TI instaspin related code, modify the ABI settings. etc. would a stock firmware could work with ORAH software?

Thanks for the effort for the project.

**Comment by fgrimminger** [comment]
Hi,

starting with building and testing one actuator module is a good approach.

1. The Antigravity 4004 motors are sold in sets of two pieces - the price per piece is around 60€.
You could use a cheaper motor if you modify the mounting interface and the motor shaft.
The ESC motor driver electronics that they sell with the motor are used for quad-copters but are not suitable for torque-control of a legged robot.

2. That's right - the encoder discs we use have 625 lines - the encoder produces 5000 pulses per turn and channel from that.
On the motor driver boards we use the rising and falling edges from the A and B channels and get 20.000 counts per revolution.
The reason why the high resolution is important for us is because the velocity is calculated from the position measurement.
For high performance control we need a velocity signal that's as smooth and precise as possible.
For that we calculate and filter the velocity signal at 10kHz on the motor driver boards - and we would like to have the highest angular resolution possible.

3. I don't understand this question.

You can also use the [Forum](https://odri.discourse.group/latest) to discuss your questions and ideas for improvements.

Best wishes. Felix
