### ISSUE TITLE
Minimum tensile strength

### ISSUE THREAD

**Issue by MEE2022** [open-dynamic-robot-initiative/open_robot_actuator_hardware#48]
I understand you recommend the lower legs be manufactured using carbon fiber, but do you have some minimum strength parameters on this part?  I was wondering if I might be able to resin print it using Liqcreate Strong-X ([technical resin data sheet](https://www.liqcreate.com/product/strong-x/#technical))

I know the tensile strength between carbon fiber and this resin are orders of magnitude off.  I haven't done a proper in-depth project overview to get a precise understanding of the stresses on this part.  Please excuse me if this is a stupid question.

**Comment by fgrimminger** [comment]
Hi,
that's a valid question - it's not so easy to select the right material and printing technology for the different parts.
So far we've been mostly using lower legs that were printed on an FDM printer with [PC-ABS material](https://www.stratasys.com/contentassets/0cbbbe43e9ab4200a16c507eb99ebe7e/mds_fdm_pc-abs_0222a2.pdf?v=49c744).
For the quadrupeds we're using the [lower leg v2](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/general/lower_legs.md#lower-leg-v2) with sparse infill to reduce the weight. 
We haven't broken any lower legs yet - so the tensile strength has not been an issue.
What seems more problematic is that the low lateral stiffness of the lower legs that can lead to vibrations depending on the gait and the gain and damping settings of the controller.
That's why we have reinforced the biped lower legs with [carbon fiber layer](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/biped_leg_3dof_v1/README.md#lower-leg-with-passive-ankle-joint). We have also used lower legs from an Markforged printer that has the capability to embed continuous fibers inside of the part.

To answer your question:
I would recommend to start printing the lower legs v2 on an FDM printer with sparse infill.
You could also try to print lower legs on your resin printer - the v2 version will be pretty heavy, because I don't think that you can print sparse structures inside of the part. So you could use the [v3 lower leg version](https://github.com/open-dynamic-robot-initiative/open_robot_actuator_hardware/blob/master/mechanics/general/lower_legs.md#lower-leg-v3) that is made for solid printing.  You could print the lower legs with both materials and see what works best for you.

 I'd be mostly concerned about the low impact resistance of the photopolymer materials - our experience is that those materials are rather brittle and break or crack easily under impact loading. You can also see that in the datasheet  - the IZOD Impact value is only 20 J/m. For the FDM material it's around 240 J/m with the printing orientation that we  use.
