### ISSUE TITLE
center pulley

### ISSUE THREAD

**Issue by f-e-l-i-x** [open-dynamic-robot-initiative/open_robot_actuator_hardware#5]
Would it be possible to produce the center pulley by wire EDM in a "2D" design, without post-processing in a lathe? 

The center pulley would then be cut with a through hole like the motor pulley and a shaft would be inserted into the hole. 

Would this suffice for the center pulley to be rotationally supported by its bearings or is a flat surface facing the center pulley bearings unsuitable?

**Comment by fgrimminger** [comment]
You could try it....
The problem is that the pulley has a larger diameter than the outer ring of the bearing.
So the pulley could rub on the outer ring or on the shell structure. (see screenshot)
You probably want to add small spacers to prevent that from happening.
Best. Felix
![center_pulley](https://user-images.githubusercontent.com/53785782/71904272-1c555100-3166-11ea-961a-25149cac5cbe.png)
