### ISSUE TITLE
Q: what's the total estimated cost of the hardware?

### ISSUE THREAD

**Issue by mw66** [open-dynamic-robot-initiative/open_robot_actuator_hardware#50]
Just want to get a rough idea.

Thanks.

**Comment by fgrimminger** [comment]
The price of the robot is difficult to estimate precisely since it will depend on the suppliers and machine shops that you use, the country you are in and the part quantities that you are ordering.

We have estimated the material cost for our Solo12 robot at around 6300€ + tax.
That is not including the imu which is the most expensive part on the robot.

PAL Robotics offers a kit with all the parts and alternatively a preassembled robot.
You can request a quote here: https://solo.pal-robotics.com/solo

**Comment by fpgirard** [comment]
Does the Solo team have a preferred forum in which prospective developers can share ideas, lessons learned, or feedback?   Posting questions and answers in Git 'Issues' doesn't seem like the best place for exchanges like cost.    
Having spent a few hours yesterday evening and this morning reviewing how a budget-conscious hobbyist such as myself would build Solo8, it seems that there are just a few components that contribute the majority of the cost - specifically the IMU (1500USD), the rotors (8*75=600USD), and microdriver modules (200USD).   

I'm not wise enough to know why the Solo needs such an expensive IMU when there are inexpensive, [MEMS-based IMU boards](https://www.seeedstudio.com/Grove-IMU-10DOF-v2-0.html) available in the 20USD range.   Many of these low cost boards are being used in highly demanding vehicles like quadcopter drones.  Using these inexpensive IMUs would also remove the master board V2 1AMP 3.3V voltage regulator and would use I2C instead of uart.   Is there something that I'm overlooking regarding the Lord IMUs that Solo needs to justify this high cost?   The T-motor rotors are nearly 2x the price of ubiquitous SunnySky motors (https://tinyurl.com/hk6dmdcu).  Most of us can afford paying 30USD per rotor but 74USD is too much.

While a master board isn't super expensive (35USD) it seems that the master board V2 could have been a simpler design by building a [shield](https://tinyurl.com/yc2xc48j) for one of the popular ESP32 boards (e.g. Lolin/Wemos ESP32S2 board or [Adafruit's 19USD ESP32S2 offering](https://learn.adafruit.com/adafruit-metro-esp32-s2/pinouts)).  The shield would consist of the TI decoupler for the 8 SPI connections, an I2 interface to the lesser expensive IMU, and ?   Do we really need a wired ethernet port?

While I'd love to build a Solo8, these components price me out as it does most hobbyists who are very intrigued by the work that your team is doing.   We want to participate but can't afford it!

**Comment by easybuildtech** [comment]
Hi Pascal, check out https://odri.discourse.group/categories for a discussion forum.

**Comment by fpgirard** [comment]
@easybuildtech - this is perfect - thank you.   I'm a huge fan of the University of Maryland where many of my interns matriculate.   Some of them are at JPL now (Nick R and Camden S.).    I'm liking what UMCP is posting [here](https://odri.discourse.group/t/interested-in-making-a-modified-less-expensive-solo12/140) - it's consistent with my initial observations.

**Comment by thomasfla** [comment]
Hi, thanks for your interest!
indeed the [forum](https://odri.discourse.group/) is the good place to discuss such topic.

I can start here with a few element of answer. 
Despite being mostly 3d printed, solo and other ODRI robots are not low cost. At least not optimized for cost.
Those robots are used as platform to experiment and develop state of the art research. For academia, it make much more sense to invest in quality sensor and cutting edge compact electronic that ease our life while experimenting. 

I can understand how this can be frustrating from a hobbyist point of view, but I think you can find all the resources on this GitHub and in the forum to replace some components, design different actuators, etc.  Actually, you will find in the forum some threads about lower cost alternative to the choices made in the project.

About specific question / suggestion:

- Yes a low cost IMU could be used, with a more complex state estimation and calibration, but I would still expect a decrease of performances.
- The master-board is a compact design. Using a shield and standard dev board is possible but would take more space, In Solo12 we have very few margin. The Ethernet is a must to do high frequency feedback loop with a computer.
- The motor could be different, but some CAD adjustment are needed to accommodate for different size, and fixture.
- The cost is also due to the custom electronic to control the motor, Other lower cost project exist, but are not as compact nor adapted to our need.
 
Please understand that we would love to see spin-off of this project optimizing cost, exploring different design choices but we can not invest our work time to do it our-self.

I hope this helps,
Thomas.

**Comment by MEE2022** [comment]
What is the estimated cost of the biped hardware (if you don't count the 3d printed parts)?

**Comment by easybuildtech** [comment]
@MEE2022 I have been noting costs, on a BOM, as I build if it helps:  https://easybuildtech.com/open-dynamic-robot-initiative-bolt-cost-breakdown/

I am in the U.S.

**Comment by MEE2022** [comment]
Thank you very much.  This is very detailed and extremely helpful.

**Comment by fgrimminger** [comment]
@easybuildtech 
Great! Thanks for sharing!
